name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        coverage: none
        tools: composer:v2
      
    - name: Composer
      run: |
        cd app
        composer install
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smhagit/website-backend:latest
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the Docker image
      run: docker push smhagit/website-backend
